"use client";
import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight, BriefcaseBusiness, CheckCircle2, ChevronRight, Moon, Search, Sun, MapPin, Users, Zap, Building2, Heart, Code2, Megaphone, Palette } from "lucide-react";
import { useTheme } from "next-themes";
import { JobCard } from "@/components/job-card";
import { jobs } from "@/lib/mock-data";

const categories = [["Design", "1,240 jobs", Palette], ["Engineering", "2,890 jobs", Code2], ["Product", "860 jobs", Zap], ["Marketing", "620 jobs", Megaphone], ["People & HR", "410 jobs", Users], ["Operations", "530 jobs", Building2]];
export default function Home() { const { theme, setTheme } = useTheme(); return <main className="overflow-hidden bg-[#fcfbff] text-zinc-900 dark:bg-zinc-950 dark:text-zinc-50">
  <nav className="sticky top-0 z-30 border-b border-transparent bg-[#fcfbff]/80 backdrop-blur-xl dark:bg-zinc-950/80"><div className="mx-auto flex h-18 max-w-7xl items-center justify-between px-5 lg:px-8"><Link href="/" className="flex items-center gap-2 text-lg font-bold tracking-tight"><span className="grid h-8 w-8 place-items-center rounded-lg bg-violet-600 text-white"><BriefcaseBusiness size={17}/></span>Hirely</Link><div className="hidden items-center gap-7 text-sm font-medium text-zinc-600 md:flex dark:text-zinc-300"><a href="#jobs">Find jobs</a><a href="#how">How it works</a><a href="#companies">For companies</a></div><div className="flex items-center gap-2"><button aria-label="Toggle theme" onClick={() => setTheme(theme === "dark" ? "light" : "dark")} className="rounded-lg p-2 text-zinc-500 hover:bg-zinc-100 dark:hover:bg-zinc-800">{theme === "dark" ? <Sun size={17}/> : <Moon size={17}/>}</button><Link href="/login" className="hidden px-3 py-2 text-sm font-semibold sm:block">Log in</Link><Link href="/signup" className="rounded-lg bg-zinc-950 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-violet-600 dark:bg-white dark:text-zinc-950">Get started</Link></div></div></nav>
  <section className="relative"><div className="absolute left-1/2 top-0 -z-0 h-96 w-[56rem] -translate-x-1/2 rounded-full bg-violet-200/50 blur-3xl dark:bg-violet-900/30"/><div className="relative z-10 mx-auto max-w-7xl px-5 pb-20 pt-20 text-center lg:px-8 lg:pt-28"><motion.div initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="mx-auto inline-flex items-center gap-2 rounded-full border border-violet-200 bg-white/70 px-3 py-1.5 text-xs font-semibold text-violet-700 shadow-sm dark:border-violet-900 dark:bg-zinc-900 dark:text-violet-300"><span className="h-1.5 w-1.5 rounded-full bg-violet-500"/>The job search, reimagined</motion.div><motion.h1 initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{delay:.08}} className="mx-auto mt-7 max-w-4xl text-5xl font-semibold tracking-[-.055em] sm:text-6xl lg:text-7xl">Work that makes <span className="text-violet-600">your next chapter</span> count.</motion.h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-zinc-600 dark:text-zinc-300">Discover roles at companies building the future. A more human way to find work you’ll genuinely love.</p>
    <form action="/dashboard/jobs" className="mx-auto mt-10 flex max-w-3xl flex-col gap-2 rounded-2xl border border-zinc-200 bg-white p-2 shadow-xl shadow-violet-200/30 sm:flex-row dark:border-zinc-800 dark:bg-zinc-900 dark:shadow-none"><label className="flex flex-1 items-center gap-3 px-3"><Search size={19} className="text-violet-600"/><input aria-label="Job title" className="h-11 w-full bg-transparent text-sm outline-none placeholder:text-zinc-400" placeholder="Job title, skill, or company"/></label><div className="hidden w-px bg-zinc-200 sm:block dark:bg-zinc-700"/><label className="flex flex-1 items-center gap-3 px-3"><MapPin size={19} className="text-violet-600"/><input aria-label="Location" className="h-11 w-full bg-transparent text-sm outline-none placeholder:text-zinc-400" placeholder="City, state, or remote"/></label><button className="rounded-xl bg-violet-600 px-7 py-3 text-sm font-semibold text-white transition hover:bg-violet-700">Search jobs</button></form>
    <div className="mt-6 flex justify-center gap-5 text-xs text-zinc-500"><span>Popular:</span><a href="#jobs">Product designer</a><a href="#jobs">Software engineer</a><a href="#jobs">Remote</a></div></div></section>
  <section className="border-y border-zinc-200 bg-white py-8 dark:border-zinc-800 dark:bg-zinc-900"><div className="mx-auto flex max-w-6xl flex-wrap items-center justify-center gap-x-12 gap-y-5 px-5 text-sm font-semibold tracking-tight text-zinc-400"><span className="text-xs font-medium uppercase tracking-widest text-zinc-400">Teams hire with</span>{["Vercel", "notion", "FIGMA", "Linear", "Webflow"].map(x=><span key={x}>{x}</span>)}</div></section>
  <section id="jobs" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="flex items-end justify-between"><div><p className="text-sm font-semibold text-violet-600">CURATED FOR YOU</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Jobs worth getting excited about.</h2></div><Link href="/dashboard/jobs" className="hidden items-center gap-1 text-sm font-semibold text-violet-600 sm:flex">View all jobs <ArrowRight size={16}/></Link></div><div className="mt-9 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{jobs.slice(0,6).map(j=><JobCard key={j.id} job={j}/>)}</div></section>
  <section id="how" className="bg-zinc-950 py-24 text-white"><div className="mx-auto max-w-7xl px-5 lg:px-8"><p className="text-sm font-semibold text-violet-400">A BETTER WAY</p><div className="mt-3 flex flex-col justify-between gap-8 md:flex-row"><h2 className="max-w-xl text-4xl font-semibold tracking-tight">Less searching. More finding your place.</h2><p className="max-w-sm text-zinc-400">A focused, thoughtful experience built around the things that matter to your career.</p></div><div className="mt-14 grid gap-8 md:grid-cols-3">{[["01","Tell us what matters","Set your preferences and we’ll bring relevant opportunities to you."],["02","Discover your fit","See the people, culture, and real work behind every listing."],["03","Make your move","Apply with confidence and track every conversation in one place."]].map(([n,t,d])=><div key={n} className="border-t border-zinc-700 pt-5"><span className="text-sm font-mono text-violet-400">{n}</span><h3 className="mt-6 text-xl font-semibold">{t}</h3><p className="mt-3 leading-7 text-zinc-400">{d}</p></div>)}</div></div></section>
  <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-semibold text-violet-600">EXPLORE</p><h2 className="mt-2 text-4xl font-semibold tracking-tight">A role for every kind of curiosity.</h2><p className="mt-4 max-w-md leading-7 text-zinc-600 dark:text-zinc-300">Browse teams that value what you bring — whether you’re ready to build, design, lead, or explore.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{categories.map(([name,count,Icon])=>{const I=Icon as typeof Palette; return <Link href="/dashboard/jobs" key={name as string} className="rounded-2xl border border-zinc-200 bg-white p-5 transition hover:border-violet-300 hover:shadow-lg dark:border-zinc-800 dark:bg-zinc-900"><I className="text-violet-600" size={22}/><p className="mt-6 font-semibold">{name as string}</p><p className="mt-1 text-xs text-zinc-500">{count as string}</p></Link>})}</div></div></section>
  <section id="companies" className="mx-auto max-w-7xl px-5 pb-24 lg:px-8"><div className="rounded-3xl bg-violet-600 px-7 py-12 text-white sm:px-14 sm:py-16"><div className="max-w-2xl"><p className="text-sm font-bold tracking-wide text-violet-200">YOUR NEXT GREAT MOVE</p><h2 className="mt-3 text-4xl font-semibold tracking-tight sm:text-5xl">The right role is out there. Let’s find it.</h2><p className="mt-5 text-violet-100">Join 50,000+ people taking the next step in their careers with clarity and momentum.</p><Link href="/signup" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-bold text-violet-700 transition hover:bg-violet-50">Create your profile <ChevronRight size={16}/></Link></div></div></section>
  <footer className="border-t border-zinc-200 bg-white py-10 dark:border-zinc-800 dark:bg-zinc-900"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 px-5 text-sm text-zinc-500 sm:flex-row lg:px-8"><div><div className="flex items-center gap-2 font-bold text-zinc-900 dark:text-white"><span className="grid h-7 w-7 place-items-center rounded-md bg-violet-600 text-white"><BriefcaseBusiness size={15}/></span>Hirely</div><p className="mt-3">Work that moves you forward.</p></div><div className="flex gap-6"><a href="#">Privacy</a><a href="#">Terms</a><a href="#">Contact</a></div></div></footer>
</main>; }
