spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/job_portal
spring.datasource.username=postgres
spring.datasource.password=Deekshi@260104

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
